/* Generated By:JavaCC: Do not edit this line. ECConstants.java */
package ECC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ECConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int TIPO = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int BYTE = 11;
  /** RegularExpression Id. */
  int SHORT = 12;
  /** RegularExpression Id. */
  int LONG = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int BOOLEAN = 17;
  /** RegularExpression Id. */
  int LITERALS = 18;
  /** RegularExpression Id. */
  int SL = 19;
  /** RegularExpression Id. */
  int ML = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "<TIPO>",
    "\"int\"",
    "\"String\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"char\"",
    "\"boolean\"",
    "<LITERALS>",
    "<SL>",
    "<ML>",
  };

}
